### PR TITLE
Made the modal header display properly

### PR DESCRIPTION
**Pull request by aldahl**
It's not pretty, and I'm sure it's not the most elegant way to do it, but it does display correctly now.

### CODE REVIEW

**Comment by webnard** [comment]
Does this work with different resolutions?

**Comment by aldahl** [comment]
Mostly, but not perfectly. The square corners stick out of the rounded ones on lower resolutions. I haven't been able to test it on any high resolutions though.

**Comment by webnard** [comment]
Nice! Did you get the dimensions by eyeballing it, or are they based in a specific calculation?

**Comment by aldahl** [comment]
I calculated it based on the window's position and border/padding, but it still wasn't perfect, so I eyeballed it from there. I eyeballed it on a 1920x1080 resolution because I thought it would be pretty generic. Do you have any suggestions on how to better do this?

**Comment by webnard** [comment]
No, what you've done should work fine. If there was some science to it, I
thought the values could be stored in variables, but since there was some
eyeballing it's OK.

How does it look on the check-out page after a fresh npm install and hard
refresh?

On Tue, Jun 9, 2015 at 12:20 PM, Alexander Dahl notifications@github.com
wrote:

> I calculated it based on the window's position and border/padding, but it
> still wasn't perfect, so I eyeballed it from there. I eyeballed it on a
> 1920x1080 resolution because I thought it would be pretty generic. Do you
> have any suggestions on how to better do this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BYU-ODH/byu-odh.github.io/pull/1#issuecomment-110454204
> .

## 

 ian hunter

**Comment by aldahl** [comment]
Looks good (at this resolution, anyway).

**Comment by webnard** [comment]
Sweet. And if you scale your window at all, does it still look okay?

On Tue, Jun 9, 2015 at 1:16 PM, Alexander Dahl notifications@github.com
wrote:

> Looks good (at this resolution, anyway).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BYU-ODH/byu-odh.github.io/pull/1#issuecomment-110469072
> .

## 

 ian hunter

**Comment by webnard** [comment]
If so, merge it on in!

On Tue, Jun 9, 2015 at 1:17 PM, Ian Hunter beanland2@gmail.com wrote:

> Sweet. And if you scale your window at all, does it still look okay?
> 
> On Tue, Jun 9, 2015 at 1:16 PM, Alexander Dahl notifications@github.com
> wrote:
> 
> > Looks good (at this resolution, anyway).
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/BYU-ODH/byu-odh.github.io/pull/1#issuecomment-110469072
> > .
> 
> ## 
> 
>  ian hunter

## 

 ian hunter

**Comment by aldahl** [comment]
It's done.

**Comment by webnard** [comment]
I'll rebuild the master branch of BYU/hlrdesk so we can test on the
development server.

On Tue, Jun 9, 2015 at 1:27 PM, Alexander Dahl notifications@github.com
wrote:

> It's done.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BYU-ODH/byu-odh.github.io/pull/1#issuecomment-110475572
> .

## 

 ian hunter

**Pull request merged**
